base: /
errorHandling: {  }
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
  -
    title: Deutsch
    enabled: true
    languageId: 1
    base: /de
    locale: de_DE.UTF-8
    navigationTitle: German
    flag: de
rootPageId: 1
routes: {  }
